sipRcouchdb:
  container_name: sipRcouchdb
  image: fedora/couchdb
  ports:
     - "5984:5984"
sipRconsul:
  image: gliderlabs/consul-server
  command: -node siprconsul -bootstrap -client 0.0.0.0 -domain sipr
  ports:
  - "8400:8400"
  - "8500:8500"
  - "8600:8600"